// Code generated by goctl. DO NOT EDIT!
// Source: cms.proto

package cmsclient

import (
	"context"

	"kapok-admin/service/addons/cms/cms"

	"github.com/tal-tech/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CmsConfigReq  = cms.CmsConfigReq
	CmsConfigResp = cms.CmsConfigResp

	Cms interface {
		GetCmsConfig(ctx context.Context, in *CmsConfigReq, opts ...grpc.CallOption) (*CmsConfigResp, error)
	}

	defaultCms struct {
		cli zrpc.Client
	}
)

func NewCms(cli zrpc.Client) Cms {
	return &defaultCms{
		cli: cli,
	}
}

func (m *defaultCms) GetCmsConfig(ctx context.Context, in *CmsConfigReq, opts ...grpc.CallOption) (*CmsConfigResp, error) {
	client := cms.NewCmsClient(m.cli.Conn())
	return client.GetCmsConfig(ctx, in, opts...)
}
