// Code generated by goctl. DO NOT EDIT.
package types

type Beid struct {
	Beid int64 `json:"beid"`
}

type Token struct {
	Token string `json:"token"`
}

type WxTicket struct {
	Ticket string `json:"ticket"`
}

type Application struct {
	Sname       string `json:"Sname"`       //名称
	Logo        string `json:"logo"`        // login
	Isclose     int64  `json:"isclose"`     //是否关闭
	Fullwebsite string `json:"fullwebsite"` // 全站名称
}

type SnsReq struct {
	Beid
	Ptyid   int64  `json:"ptyid"`    //对应平台
	BackUrl string `json:"back_url"` //登陆返回的地址
}

type SnsResp struct {
	Beid
	Ptyid    int64  `json:"ptyid"`     //对应平台
	Appid    string `json:"appid"`     //sns 平台的id
	Title    string `json:"title"`     //名称
	LoginUrl string `json:"login_url"` //微信登陆的地址
}

type WxShareResp struct {
	Appid     string `json:"appid"`
	Timestamp int64  `json:"timestamp"`
	Noncestr  string `json:"noncestr"`
	Signature string `json:"signature"`
}

type RegisterReq struct {
	Mobile   string `json:"mobile"` //基本一个手机号码就完事
	Password string `json:"password"`
	Smscode  string `json:"smscode"` //短信码
}

type SetMobileReq struct {
	Uid       int64  `json:"uid"`
	Mobile    string `json:"mobile"`    //旧手机号码
	NewMobile string `json:"newmobile"` //新手机号码
	Smscode   string `json:"smscode"`   //短信码
}

type LoginReq struct {
	Mobile   string `json:"mobile"`
	Type     int64  `json:"type"` //1.密码登陆，2.短信登陆
	Password string `json:"password"`
}

type WxLoginReq struct {
	Beid  int64  `json:"beid"`  //应用id
	Code  string `json:"code"`  //微信登陆密钥
	Ptyid int64  `json:"ptyid"` //对应平台
}

type UserReply struct {
	Auid     int64  `json:"auid"`
	Uid      int64  `json:"uid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Username string `json:"username"`
	Mobile   string `json:"mobile"`
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
	JwtToken
}

type AppUser struct {
	Uid      int64  `json:"uid"`
	Auid     int64  `json:"auid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
}

type LoginAppUser struct {
	Uid      int64  `json:"uid"`
	Auid     int64  `json:"auid"`
	Beid     int64  `json:"beid"`  //应用id
	Ptyid    int64  `json:"ptyid"` //对应平台
	Nickname string `json:"nickname"`
	Openid   string `json:"openid"`
	Avator   string `json:"avator"`
	JwtToken
}

type JwtToken struct {
	AccessToken  string `json:"access_token,omitempty"`
	AccessExpire int64  `json:"access_expire,omitempty"`
	RefreshAfter int64  `json:"refresh_after,omitempty"`
}

type UserReq struct {
	Auid  int64 `json:"auid"`
	Uid   int64 `json:"uid"`
	Beid  int64 `json:"beid"`  //应用id
	Ptyid int64 `json:"ptyid"` //对应平台
}

type Request struct {
	Name string `path:"name,options=you|me"`
}

type Response struct {
	Message string `json:"message"`
}
