// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	common "kapok/kapok-admin/apps/internal/handler/common"
	user "kapok/kapok-admin/apps/internal/handler/user"
	"kapok/kapok-admin/apps/internal/svc"

	"github.com/tal-tech/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/common/appinfo",
				Handler: common.AppInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/common/snsinfo",
				Handler: common.SnsInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/common/wx/ticket",
				Handler: common.WxTicketHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/common/qiuniu/token",
				Handler: common.QiuniuTokenHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/ping",
				Handler: user.PingHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/wx/login",
				Handler: user.WxloginHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/wx/login",
				Handler: user.Code2SessionHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.Usercheck},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/user/info",
					Handler: user.UserInfoHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/user/setmobile",
					Handler: user.SetMobileHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)
}
