// Code generated by goctl. DO NOT EDIT!
// Source: scrm.proto

package server

import (
	"context"

	"kapok-admin/service/addons/scrm/internal/logic"
	"kapok-admin/service/addons/scrm/internal/svc"
	"kapok-admin/service/addons/scrm/scrm"
)

type ScrmServer struct {
	svcCtx *svc.ServiceContext
}

func NewScrmServer(svcCtx *svc.ServiceContext) *ScrmServer {
	return &ScrmServer{
		svcCtx: svcCtx,
	}
}

func (s *ScrmServer) GetScrmConfig(ctx context.Context, in *scrm.ScrmConfigReq) (*scrm.ScrmConfigResp, error) {
	l := logic.NewGetScrmConfigLogic(ctx, s.svcCtx)
	return l.GetScrmConfig(in)
}
